version: "3.6"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=skeleton
      - POSTGRES_USER=skeleton
      - POSTGRES_DB=skeleton
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  db_test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "54321:5432"
    volumes:
      - data-test:/var/lib/postgresql/data

volumes:
  data: {}
  data-test: {}
    